---
title: "Week 1: Lab"
subtitle: "Making maps with `tmap`"
author: "Jackson Coldiron"
date: 2025-10-2
execute: 
  eval: true
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---
## Get Started
```{r}
# Load packages
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

```{r}
# Read in spatial objects for Rapa Nui
ei_points <- st_read(here("week1", "data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("week1", "data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here("week1", "data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here("week1", "data", "easter_island", "ei_roads.gpkg"))
```

## 2. Single-object map
```{r}
# Create a single object map with tmap
tm_shape(ei_borders) +
  tm_borders()
```
## 3. Multi-Object Map
```{r}
tm_shape(ei_borders) +
  tm_borders() +
  tm_shape(ei_elev) +
  tm_raster() +
  tm_shape(ei_points) +
  tm_dots() +
  tm_shape(ei_roads) +
  tm_lines()
  
```
## 4. Interactive Map
```{r}
# Switch from the default plot mode to view
tmap_mode("view")
tmap_mode("plot")

# Plot interactive
ei_map <- tm_shape(ei_elev) + # Start with elevation
  tm_graticules() + # Add in gridlines
  tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"), # Customize color scaling
            col.legend = tm_legend("Elevation (m asl)")) + # Add legend title
  tm_shape(ei_borders) + 
    tm_borders() +
  tm_shape(ei_roads) +
    tm_lines() +
  tm_shape(ei_points) +
    tm_symbols(shape = 24, 
               size = "elevation", 
               size.legend = tm_legend("Volcanoes (m asl)")) +
  tm_compass(position = c("right", "top")) +
  tm_scalebar() +
  tm_title("Easter Island")

ei_map
```

## 5. Create Map with ggplot
```{r}
# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)

# Plot
ggplot() +
  # first add Easter Isand borders
  geom_sf(data = ei_borders, color = "#212529") +
  # add elevation raster
  geom_stars(data = ei_elev) +
  scale_fill_distiller(name = "Elevation (m asl)", # legend title with units
                       palette = "RdYlGn",         # red-yellow-green palette (no need to reverse)
                       na.value = "lightblue") +  # set NA color (background ocean)
  # add road vector
  geom_sf(data = ei_roads, color = "#343a40") +
  # add volcano vector
  geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, 
                 size = elevation), # point size depends on attribute value
             shape = 17,            # triangle
             color = "#22577a") +
  scale_size_continuous(name = "Volcanoes (m asl)") +       # legend title with units
  ggspatial::annotation_north_arrow(location = "br",        # bottom right
                                    which_north = "true") + # point to north pole
  ggspatial::annotation_scale(location = "bl",              # bottom left
                              width_hint = 0.5) +           # proportion of map area the scalebar should occupy
  labs(title = "Easter Island") +
  theme_minimal()
```

